### ISSUE TITLE
(MacOS) Install failing: Could not compare "6.0.0-alpha" to "5.0". Error...

### ISSUE THREAD

**Issue by chrber** [Microsoft/Docker-PowerShell#125]
**Output of `$PSVersionTable` (from a powershell process):**

```
PS /Users/<username>/.local/share/powershell/Modules> $PSVersionTable.PSVersion

Major Minor Patch Label
----- ----- ----- -----
    6     0     0 alpha
```

**Output of `ipmo Docker; (module Docker).Version.ToString()` (from a powershell process):**

```
(paste your output here)
```

**Steps to reproduce the issue:**
1. Register-PSRepository -Name DockerPS-Dev -SourceLocation https://ci.appveyor.com/nuget/docker-powershell-dev
2.Install-Module Docker -Repository DockerPS-Dev
3.

**What actually happened?:**
I am on a MacOS system 10.11.6 and have installed the PowerShell from here: https://github.com/PowerShell/PowerShell

After that I tried installing the docker module, with the complete error:

PS /Users/<userName>/.local/share/powershell/Modules> Install-Module Docker -Repository DockerPS-Dev

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its InstallationPolicy value by
running the Set-PSRepository cmdlet. Are you sure you want to install the modules from 'DockerPS-Dev'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): A
     PackageManagement\Install-Package : Could not compare "6.0.0-alpha" to "5.0". Error: "Cannot convert value "5.0" to type          "System.Management.Automation.SemanticVersion". Error: "Cannot process argument because the value of argument "version" is not valid.  Change the value of the "version" argument and run the operation again.""                                                              At /usr/local/microsoft/powershell/6.0.0-alpha.9/Modules/PowerShellGet/PSModule.psm1:1706 char:21oooooooooooooooooooooooooooooooooooo] + ...          $null = PackageManagement\Install-Package @PSBoundParameters                                                            +                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : ComparisonFailure,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

**What did you expect to happen?:**
Successful Installation

**Additional information:**

**Comment by swernli** [comment]
Hi @chrber, thanks for giving our cmdlets a try!  Unfortunately, we haven't actually checked in the support for cross-platform PowerShell yet (I'm still fighting with our appveyor build over at https://github.com/Microsoft/Docker-PowerShell/pull/124).  Even once that PR goes in, for the time being our dev nuget feed will be Windows only (we are working on a solution for that, and to make sure we don't lose track, I filed https://github.com/Microsoft/Docker-PowerShell/issues/126).

In the meantime, if you are willing, you try compiling the contents of https://github.com/swernli/docker-powershell/tree/unix-support and seeing if that works for you?  A word of warning: we haven't tried compiling or running on OSX yet, so you'd be blazing the trail, and one known limitation is that interactive connections to containers will currently throw "Not Supported" when trying to run on OSX.  If you'd rather wait for us to produce a package, I understand, and we will try to get that together soon.

We appreciate any input or contributions you might have, and look forward to seeing how this works for you when the rest of the pieces come together!

@jstarks @jterry75 FYI.

**Comment by bgelens** [comment]
FYI: Workaround is available using Install-Package https://github.com/PowerShell/PowerShell/issues/1773

**Comment by swernli** [comment]
@chrber I believe this issue should be fixed with the latest powershell version.  Can you retry and confirm?

**Comment by swernli** [comment]
I'll close this issue for now, as I believe the latest powershell resolves it.  Please re-open if you are still experiencing the problem.

**Comment by chrber** [comment]
Shall I open another issue as I now have a different problem or shall we go on in this issue?

PS /Users/bernardt> Install-Module Docker -Repository DockerPS-Dev
     PackageManagement\Install-Package : Could not find a part of the path                                                             '/usr/local/microsoft/powershell/6.0.0-alpha.11/Modules/Docker/0.1.0.111'.                                                             At /usr/local/microsoft/powershell/6.0.0-alpha.11/Modules/PowerShellGet/PSModule.psm1:1823 char:21                                     + ...          $null = PackageManagement\Install-Package @PSBoundParametersoooooooooooooooooooooooooooooooooooooooooooooooooooooooooo] +                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                + CategoryInfo          : NotSpecified: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : System.IO.DirectoryNotFoundException,Microsoft.PowerShell.Commands.CopyItemCommand,Microsoft.PowerShell
   .PackageManagement.Cmdlets.InstallPackage

**Comment by jterry75** [comment]
Can you install anything from PowerShell? I think this bug is not specific to the package and its possible that is specific to PowerShell itself on OSX. Maybe we should open the bug on their side?
