### ISSUE TITLE
Case-Sensitive Container Network Names?

### ISSUE THREAD

**Issue by markjmorgan** [Microsoft/Docker-PowerShell#144]
New-ContainerNetwork names appear to be case-sensitive.  Is that a Docker thing or should this be made case-insensitive more in keeping with PowerShell?

**Comment by swernli** [comment]
@markjmorgan This was actually design choice on the part of the Windows networking stack that sits below the docker daemon, so whether you use these cmdlets or docker cli it still remains case sensitive.
