### ISSUE TITLE
Issue OneGet NuGet provider 2.8.5.207

### ISSUE THREAD

**Issue by jianyunt** [Microsoft/Docker-PowerShell#145]
Hi, we see an issue https://github.com/NuGet/Home/issues/3495 saying something with the new version of the OneGet (PackageManagement) provider 2.8.5.207.  I looked your appveyor.yml, it looks like you are using:

WS2012R2+WMF5.1 Preview. 
nuget.exe to create a docker.nupkg.
register a package source 'test' to the local folder
use oneget/powershellget to find-module and install-module from your local share.

If the above statement is correct, the nuget provider version should not impact you.
Also if you want PowerShellGet to find or install-module, your docker.nuspec must contain tags, for example, <tags>PSModule</tags> . Otherwise, there is no way for powershellget to find docker as module.

My recommendation is to update your .nuspec to add tags to include PSModule.

**Comment by swernli** [comment]
@jianyunt It seems the nugget version does affect us: 2.8.5.207 fails but 2.8.5.206 with the same commands succeeds.  Is it possible the PSModule tag you mention is a new requirement?  Can you point me to any documentation or examples of this tag?

**Comment by jianyunt** [comment]
@bmanikm, can you please point @swernli to a PowerShellGet doc regarding the PSModule tag? thx

**Comment by bmanikm** [comment]
@swernli you have to use the PowerShellGet cmdlets to publish your modules (Publish-Module) and scripts (Publish-Script).

**Comment by jstarks** [comment]
What's the point in basing PowerShell packages on NuGet if you can't use NuGet tools to manipulate the packages?

**Comment by bmanikm** [comment]
Please note that local directory based repository can be used for both modules and scripts, so Publish cmdlets add PSModule tag for modules and PSScript tag for scripts during the publish operation. Publish cmdlets ensure that modules and scripts are valid before creating and pushing the Nupkg. 

We don't recommend users to use the NuGet tools directly to publish the modules and scripts.
What is blocking you from using the Publish-Module cmdlet here?
