### ISSUE TITLE
Please add option to pull from private registries

### ISSUE THREAD

**Issue by artisticcheese** [Microsoft/Docker-PowerShell#166]
I don't see an option to specify which registry you are pulling images from. Please add this option.

**Comment by swernli** [comment]
This works the same way it works in docker: you specify the registry as part of the repository.  So if you have a registry running on myreghost at port 5000, you would do `Request-ContainerImage -Repository myreghost:5000/myimage -Tag v1` or similar.  This is the same as doing `docker pull myreghost5000/myimage:v1`.

See https://docs.docker.com/registry/ for more details.
