### ISSUE TITLE
Docker.DotNet submodule should come from original master, not separate fork

### ISSUE THREAD

**Issue by swernli** [Microsoft/Docker-PowerShell#19]
The submodule for Docker.DotNet uses a separate fork instead of the master branch from https://github.com/ahmetalpbalkan/Docker.DotNet/.  The changes in this fork should be PR'ed back into the master branch so that Docker.PowerShell is using the same Docker.DotNet code as everything else.

**Comment by jterry75** [comment]
Alternatively now that we aren't under such active development should this just mirror master rather than a specific commit id?
