### ISSUE TITLE
Suggestion: Implement a release pipeline

### ISSUE THREAD

**Issue by RamblingCookieMonster** [Microsoft/Docker-PowerShell#24]
It would be handy if changes to the master or dev branches kicked off a pipeline to provide:

* A latest release (perhaps in AppVeyor, [similar to the DSC resources](https://blogs.msdn.microsoft.com/powershell/2015/08/27/development-builds-for-dsc-resources-are-available/))
* A stable release (perhaps based on tags, and published to the PowerShell Gallery)

This might make it easier for IT folks like myself to pull down the latest version for testing purposes : )

Cheers!

**Comment by jstarks** [comment]
That's good feedback -- we'll figure out how to get that done. It may be a little while before we have a release ready for the PS Gallery, but we should be able to set up a NuGet feed with CI builds soon.

cc @taylorb-microsoft

**Comment by jstarks** [comment]
@RamblingCookieMonster I've implemented your first suggestion -- you can get the latest release through an AppVeyor NuGet feed. The details are in README.md -- I hope you can give it a try.

We'll eventually push to the PowerShell Gallery once we have a stable release. I don't think we need this issue to track that work, so I'm going to close this.
