### ISSUE TITLE
Get-ContainerDetail does not work

### ISSUE THREAD

**Issue by jstarks** [Microsoft/Docker-PowerShell#39]
PS C:\Users\jostarks\Source\Repos\Docker-PowerShell> Get-ContainerDetails cranky_shaw
Get-ContainerDetails : Error converting value {null} to type 'System.Int64'. Path 'HostConfig.MemorySwappiness', line 1, position 1600.
At line:1 char:1
+ Get-ContainerDetails cranky_shaw
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ContainerDetails], JsonSerializationException
    + FullyQualifiedErrorId : Newtonsoft.Json.JsonSerializationException,Docker.PowerShell.Cmdlets.GetContainerDetails

**Comment by jstarks** [comment]
Seems like the marshaling stuff needs some work...

PS C:\Users\jostarks\Source\Repos\Docker-PowerShell> Get-ContainerDetails pedantic_lalande
Get-ContainerDetails : JSON integer 2147483648 is too large or small for an Int32. Path 'State.ExitCode', line 1, position 301.
At line:1 char:1
+ Get-ContainerDetails pedantic_lalande
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ContainerDetails], JsonReaderException
    + FullyQualifiedErrorId : Newtonsoft.Json.JsonReaderException,Docker.PowerShell.Cmdlets.GetContainerDetails

**Comment by jterry75** [comment]
@jstarks How exactly are you expecting this to be handled:

```c#
 [DataMember(Name = "MemorySwappiness")]
public long MemorySwappiness { get; set; }
```

This comes directly from the docker HostConfig. How would we know that this value will not always be returned? We have to either add a 1'off fix for this property or we have to make all struct values a struct? to indicate this behavior.

Ideas?

**Comment by jstarks** [comment]
In Go JSON marshaling, every scalar value is optional with a default value of 0/false/"". We should behave the same way.

**Comment by jterry75** [comment]
@jstarks Also, the second error is crazy. How does Go handle deserializing a "number" type to a sized type.

```js
{
    "State": {
        "ExitCode": 2147483648
    }
}
```
```Go
type ContainerState struct {
    ExitCode int
}
```
```C#
class ContainerState {
    [DataMember("ExitCode")]
    int ExitCode {get; set;}
}
```

This doesn't fit the max value in Go or C# which is: 1<<31 -1 == 214748364**7** which is 1 less than the return value passed.

Im not sure how we could handle this case other than writing a custom deserializer and testing int sizes or just generating everything as longs.

**Comment by jstarks** [comment]
Hmm, that's interesting. int in Go doesn't have a defined size, it's either 32 bits or 64 bits. I believe in practice it is 64 bits on 64-bit platforms. Probably we should marshal it as long, and maybe we should file some issues against engine-api wherever they use int instead of int32 or int64 specifically.

**Comment by swernli** [comment]
@jstarks This is fixed now, right?  It seems to work on my machine, but I'm not sure if my containers have the same properties set as yours did.

**Comment by jterry75** [comment]
Yes this works. All Docker Containers will have exit codes that would fail to deserialize when we weren't generating them as longs.
