### ISSUE TITLE
Get-ContainerDetails violates the singular noun rule

### ISSUE THREAD

**Issue by KirkMunro** [Microsoft/Docker-PowerShell#42]
All PowerShell commands should have a singular noun.

[Details is plural](http://english.stackexchange.com/questions/3675/is-details-singular).

Therefore, Get-ContainerDetails is in violation of this rule.  To correct this, rename Get-ContainerDetails as Get-ContainerDetail, Get-ContainerInfo, or something similar.

If you're worried about backward compatibility with the Get-ContainerDetails name already, create a Get-ContainerDetails alias in the binary module itself or in a script module file and associate that alias with the new command name.  I think this is early enough that you shouldn't be too worried about backward compatibility for this command, especially since another issue is logged against it saying it is not working.

**Comment by jstarks** [comment]
Yep, we should fix this.

In our salad days we're not worrying about backward compatibility, so there is no need for an alias.
