### ISSUE TITLE
Build-ContainerImage misbehaves with absolute paths

### ISSUE THREAD

**Issue by swernli** [Microsoft/Docker-PowerShell#46]
Build-ContainerImage unconditionally appends the provided path with the current powershell user's working directory, but that should only happen for relative paths.  Absolute paths should be used directly.

**Comment by jstarks** [comment]
Not repro on my machine... can you give an example with the -Verbose flag?

**Comment by swernli** [comment]
Yup, looks like I was still using an outdated master.  Synced up and the problem went away... though now I'm seeing issue https://github.com/ahmetalpbalkan/Docker.DotNet/issues/62 in the serialization.  I'll close this one.
