### ISSUE TITLE
Image incompatibility error for new container does not surface

### ISSUE THREAD

**Issue by bgelens** [Microsoft/Docker-PowerShell#49]
I know Containers on win10 are still early preview but I wanted to test anyway.
Unfortunately there are currently no Container Images available for Win10.
When trying to create a container with the WindowsServerCore image, Docker run responds with an exception. New-Container does not and leaves an impression it worked correctly.

![untitled](https://cloud.githubusercontent.com/assets/10071039/15006132/b6b65a62-11cd-11e6-8236-d674755aa7b0.png)

**Comment by jterry75** [comment]
The error you are seeing from docker run is actually caused at start time. In your example above you never started the container so the error was not ever hit. You would need to do a:
```PowerShell
Start-Container e1eb
```
and you should of seen the same error. Can you try that for me and tell me if your issue repros the same way between Docker CLI and Docker PowerShell?

**Comment by bgelens** [comment]
I tried and the same error got thrown.
![untitled](https://cloud.githubusercontent.com/assets/10071039/15040290/dbe25fa2-12b3-11e6-96fa-f8a296fb4630.png)
Thanks!

**Comment by neilpeterson** [comment]
There are current issues with Windows 10 and containers. That said, Windows 10 currently only supports Hyper-V containers, and Hyper-V containers only support the Nano Server base image. When things are working in Windows 10, the correct image to use will be the Nano Serer image.

thanks

**Comment by bgelens** [comment]
Thanks for this info! I got a Hyper-V Nano container running on my Win10 box. It's not entirely stable / responsive yet. I managed to connect to one but everything times out. Still happy to get it working and looking forward to things to come!
