### ISSUE TITLE
DOCKER_CERT_PATH should not imply TLS is enabled

### ISSUE THREAD

**Issue by jstarks** [Microsoft/Docker-PowerShell#52]
With docker CLI, DOCKER_CERT_PATH specifies the cert path, but the user still has to specify --tls or --tlsverify or set DOCKER_TLS_VERIFY to turn on TLS.

Probably we should actually make sure we are implementing the verification side (I think we are not) and support DOCKER_TLS_VERIFY.

**Comment by swernli** [comment]
I'm not sure I agree.  Should we also add a `-UseTLS` parameter to the cmdlets?  Would it every be correct to supply one without the other?  If they always have to both be specified, but one is just a flag and the other is a value, then I think DOCKER_CERT_PATH does indeed imply TLS and the additional flag has no value.

**Comment by swernli** [comment]
Talked offline, I see the reasoning.  I'll get this fixed soon.

**Comment by swernli** [comment]
Finally fixed by #155.
