### ISSUE TITLE
Docker.Format.ps1xml is missing from 0.0.0.28

### ISSUE THREAD

**Issue by bgelens** [Microsoft/Docker-PowerShell#54]
Install/Update-Module will fail because the Docker.Format.ps1xml is not in the published module files but is listed in the manifest.
![untitled](https://cloud.githubusercontent.com/assets/10071039/15066352/c0ff226e-1368-11e6-8d00-ee781ac9032c.png)

**Comment by jstarks** [comment]
Oops. I'll get this fixed quickly, and then we can figure out how to make sure this doesn't happen again.
