### ISSUE TITLE
Update the instruction with how to set the container host.

### ISSUE THREAD

**Issue by hdansou** [Microsoft/Docker-PowerShell#64]
It is not clear if the module already knows about  a container host.
Therefore it may be best to show how to defined or set the host.
I was getting the error below after running `Get-ContainerNetwork`

```
PS C:\> Get-ContainerNetwork
Get-ContainerNetwork : The operation has timed out.
At line:1 char:1
+ Get-ContainerNetwork
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ContainerNetwork], TimeoutException
    + FullyQualifiedErrorId : System.TimeoutException,Docker.PowerShell.Cmdlets.GetContainerNetwork
```

After following the instruction 
https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/quick_start_configure_host, I was able to get passed the error. Maybe that error could also be friendlier or explicit.

**Comment by jstarks** [comment]
This is related to #20. @swernli I think we need to put a top-level try/catch in ProcessRecord() that can handle HttpRequestExceptions, and we need to fix Docker.DotNet to return a HttpRequestException when npipe connection fails. Currently we only return this if a SocketException is thrown, I think.
