### ISSUE TITLE
How do I configure port mapping?

### ISSUE THREAD

**Issue by BenjaminArmstrong** [Microsoft/Docker-PowerShell#71]
Can't figure this one out...

**Comment by dfinke** [comment]
I'm new to docker.  Can this be done with the PS cmdlets?

`docker run -p 80:80 kitematic/hello-world-nginx`

Btw , terrific job aligning this so well with the PS way of things. It just works.

**Comment by swernli** [comment]
Answered in https://github.com/Microsoft/Docker-PowerShell/issues/174.  It's not pretty, but at least it works.  This is a prime candidate for functionality that should get wrapped into a cmdlet for usability and discovery.
