### ISSUE TITLE
new-container should take "ImageName" as a string

### ISSUE THREAD

**Issue by BenjaminArmstrong** [Microsoft/Docker-PowerShell#76]
I just want to use "nanoserver" - don't demand an object please

**Comment by swernli** [comment]
It does.  Everywhere that you see a "-Id" parameter, that also accepts the full friendly name (or partial ID).  This matches docker CLI and docker engine api, where ID doesn't mean "fully qualified alphanumeric unique identifier" but rather "full name or unique subset of ID."  Unfortunately, English is an insufficient language, and the word that means "either name or identifier" is "identifier."  So you can already do what you want to do, ie:
`new-container windowsservercore -containername test cmd /c echo test`
`start-container test -passthru`

**Comment by BenjaminArmstrong** [comment]
This is not a workable solution - few of our users will intuitively think to pass a name to an ID field.  And I do not want to spend the next couple of years telling people "Oh, ID works as Name too".  Why not just have a "imagename" parameter alias?

**Comment by swernli** [comment]
We found a good parameter alias solution in https://github.com/Microsoft/Docker-PowerShell/pull/83 that should address this and similar concerns.

**Comment by swernli** [comment]
Fixed by #83.
