### ISSUE TITLE
new-container should have a "name" parameter - not a "containername" parameter

### ISSUE THREAD

**Issue by BenjaminArmstrong** [Microsoft/Docker-PowerShell#77]
The "container" is implied

**Comment by swernli** [comment]
I did this initially to differentiate between the identifying information being provided for the image that the container is based on and the new information used on the container being created.  But if you think just "-Name" is sufficient, we can change it to that.

**Comment by BenjaminArmstrong** [comment]
Just "name" is the standard.  Check Hyper-V commandlets - we use "name" when the cmdlet includes "vm" and "vmname" when the cmdlet does not include "vm"
