### ISSUE TITLE
stop-container needs a "name" parameter

### ISSUE THREAD

**Issue by BenjaminArmstrong** [Microsoft/Docker-PowerShell#79]

**Comment by swernli** [comment]
ID is the parameter you are looking for.  Everywhere that you see a "-Id" parameter, that also accepts the full friendly name (or partial ID).  This matches docker CLI and docker engine api, where ID doesn't mean "fully qualified alphanumeric unique identifier" but rather "full name or unique subset of ID."  Unfortunately, English is an insufficient language, and the word that means "either name or identifier" is "identifier."  So you can already do what you want to do, ie:
`new-container windowsservercore -containername test cmd /c echo test`
`start-container test -passthru`
