### ISSUE TITLE
Install-ContainerOSImage got purged with Container module Win10 build 14379

### ISSUE THREAD

**Issue by bgelens** [Microsoft/Docker-PowerShell#92]
In the latest Win10 build 14379, the inbox Containers module got removed and with it, the Install-ContainerOSImage function. The ContainerImage Package Provider relies on this function to install the base OS image but now it is missing, we cannot install the base image anymore.
I get that we need to switch working with Docker API and this module but now I can't start anymore until Install-ContainerOSImage is replaced or the Package Provider installs the image in another way.

**Comment by jstarks** [comment]
@taylorb-microsoft @patricklang Can you help?

**Comment by PatrickLang** [comment]
Let me follow up - need to get some more info on what the replacement cmdlet is

**Comment by PatrickLang** [comment]
We fixed the Windows 10 insider setup steps here: https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/quick_start_windows_10 .

There is still an outstanding issue with pull requests that we're working to resolve (https://github.com/Microsoft/Virtualization-Documentation/issues/298#issuecomment-232483705), but the updated quick start guide should get you working around the deprecated cmdlet

**Comment by bgelens** [comment]
works for me, thanks!
